// AUTH ACTION TYPES
export const SIGN_UP = 'SIGN_UP';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN = 'LOG_IN';

export const SIGN_IN = 'SIGN_IN'; // Deprecated

// USER ACTION TYPES
export const FETCH_USER = 'FETCH_USER'
export const EDIT_USER = 'EDIT_USER'
export const APPLY_JOBLOG_FILTERS = 'APPLY_JOBLOG_FILTERS'

// USER STATUS TYPES
export const ACTIVE = 'ACTIVE'

// TECHNICIAN ACTION TYPES  
export const FETCH_TECHNICIAN = 'FETCH_TECHNICIAN';
export const FETCH_TECHNICIANS = 'FETCH_TECHNICIANS';
export const CREATE_TECHNICIAN = 'CREATE_TECHNICIAN';
export const UPDATE_TECHNICIAN = 'UPDATE_TECHNICIAN';
export const DELETE_TECHNICIAN = 'DELETE_TECHNICIAN';

// LEAD GENERATOR ACTION TYPES
export const FETCH_LEADGENERATOR = 'FETCH_LEADGENERATOR';
export const FETCH_LEADGENERATORS = 'FETCH_LEADGENERATORS';
export const CREATE_LEADGENERATOR = 'CREATE_LEADGENERATOR';
export const UPDATE_LEADGENERATOR = 'UPDATE_LEADGENERATOR';
export const DELETE_LEADGENERATOR = 'DELETE_LEADGENERATOR';

// JOB ACTION TYPES
export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_JOB = 'FETCH_JOB';
export const ACCEPT_JOB = 'ACCEPT_JOB';
export const REJECT_JOB = 'REJECT_JOB';
export const ASSIGN_TECHNICIAN = 'ASSIGN_TECHNICIAN';
export const FORCE_TECHNICIAN_CONFIRMATION = 'FORCE_TECHNICIAN_CONFIRMATION';
export const UPDATE_COMMISSION_RATE = 'UPDATE_COMMISSION_RATE';
export const UPDATE_JOB_VALUE = 'UPDATE_JOB_VALUE';
export const UPDATE_JOB_DESCRIPTION = 'UPDATE_JOB_DESCRIPTION';




// API TEST
export const API_TEST = 'API_TEST';